Language_edu/Language_edu/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Language_edu/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

Language_edu/students/urls.py
from django.urls import path

from . import views

app_name = 'students'

urlpatterns = [
    path('<int:pk>/edit/', views.student, name='student_edit'),
    path('<int:pk>/delete/', views.student_delete, name='student_delete'),
    path('list/', views.students_list, name='students_list'),
    path('', views.student, name='student_create'),
]

Language_edu/students/models.py
from django.db import models

from .validators import real_age


MAX_NAME_LENGTH = 20


class Teacher(models.Model):
    first_name = models.CharField('Name', max_length=MAX_NAME_LENGTH)
    last_name = models.CharField('Surname', max_length=MAX_NAME_LENGTH)

    class Meta:
        verbose_name = 'Teacher'
        verbose_name_plural = 'Teachers'

    def __str__(self):
        if self.last_name:
            return f'{self.first_name} {self.last_name}'
        else:
            return self.first_name


class Student(models.Model):
    first_name = models.CharField('Name', max_length=MAX_NAME_LENGTH)
    last_name = models.CharField(
        'Surname', blank=True, max_length=MAX_NAME_LENGTH
    )
    birthday = models.DateField('Date of birth', validators=(real_age,))
    image = models.ImageField(
        upload_to='students/photos/',
        null=True,
        blank=True,
        default=None,
        verbose_name='photo',
    )
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='students',
        verbose_name='Teacher',
    )

    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Students'
        constraints = (
            models.UniqueConstraint(
                fields=('first_name', 'last_name', 'birthday'),
                name='Unique person constraint',
            ),
        )

    def __str__(self):
        if self.last_name:
            return f'{self.first_name} {self.last_name}'
        else:
            return self.first_name

Language_edu/students/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Student


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = 'first_name', 'last_name', 'birthday', 'image', 'teacher'
        widgets = {
            'birthday': forms.DateInput(
                attrs={'type': 'date'}, format='%Y-%m-%d'
            ),
            'image': forms.FileInput(attrs={'class': 'form-control'})
        }

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        return first_name.split()[0]

    def clean(self):
        super().clean()
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']

Language_edu/pages/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'pages/index.html')

Language_edu/students/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator

from .forms import StudentForm
from .models import Student


STUDENTS_PER_PAGE = 7


def students_list(request):
    students = Student.objects.order_by('id')
    paginator = Paginator(students, STUDENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'students/students_list.html', context)


def student(request, pk=None):
    if pk is not None:
        isinstance = get_object_or_404(Student, pk=pk)
    else:
        isinstance = None

    form = StudentForm(
        request.POST or None, files=request.FILES or None, instance=isinstance
    )
    context = {'form': form}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
    return render(request, 'students/student.html', context)


def student_delete(request, pk):
    isinstance = get_object_or_404(Student, pk=pk)
    form = StudentForm(instance=isinstance)
    context = {'form': form}
    if request.method == 'POST':
        isinstance.delete()
        return redirect('students:students_list')
    return render(request, 'students/student.html', context)

Language_edu/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <title>Header</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
  </head>
  <body>
    {% include "includes/header.html" %}
    <div class="container pt-5">
      {% block content %}{% endblock %}
    </div>
    {% include "includes/footer.html" %}
  </body>
</html>

Language_edu/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© «<b>G</b>reat <b>C</b>ompany»</p>
</footer> 

Language_edu/templates/includes/header.html
<header>
  <nav class="navbar shadow-sm">
    <div class="container">
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:homepage' %} active {% endif %}"
              href="{% url 'pages:homepage' %}">
              About
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'students:student_create' %} active {% endif %}"
              href="{% url 'students:student_create' %}">
              Add a student
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'students:students_list' %} active {% endif %}"
              href="{% url 'students:students_list' %}">
              List of students
            </a>
          </li>
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

Language_edu/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Previous
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Next
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Last
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

Language_edu/templates/pages/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Header</h1>
  <p>Whatever you think you need to convey to everyone about the company, you can post here.</p>
{% endblock %}

Language_edu/templates/students/student.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  {% with data=form.instance %}
    {% if '/edit/' in request.path %}
      <h1>Edit {{ data.first_name }} {{ data.last_name }}</h1>
    {% elif "/delete/" in request.path %}
      <h1>Delete {{ data.first_name }} {{ data.last_name }}</h1>
    {% else %}
      <h1>Create record</h1>
    {% endif %}
    <div class="card col-4 m-3">
      <div class="card-header">
        Student's card
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not "/delete/" in request.path %}
            {% bootstrap_form form %}
            {% if data.image %}
              <img src="{{ data.image.url }}" height="100">
            {% endif %}
            <div id="imagePreview"></div>
          {% else %}
            <p>{{ data.first_name }} {{ data.last_name }}</p>
            <p>{{ data.birthday }}</p>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Submit" %}
        </form>
      </div>
    </div>
  {% endwith %}
{% endblock %}

Language_edu/templates/students/students_list.html
{% extends "base.html" %}

{% block content %}
  {% for student in page_obj %}
    <div class="row">
      <div class="col-2">  
        {% if student.image %}
          <img src="{{ student.image.url }}" height="100">
        {% endif %}
      </div>

      <div class="col-10">  
        <div>
          {{ student.first_name }} {{ student.last_name }} — {{ student.birthday }}
        </div>
        <div>
          <a href="{% url 'students:student_edit' student.id %}">Edit record</a> | <a href="{% url 'students:student_delete' student.id %}">Delete record</a>
        </div>
      </div>
      {% if not forloop.last %}
        <hr class="mt-3"> 
      {% endif %}
    </div>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %} 